[project]
name = "examples"
version = "0.1.0"
description = "teenygrad examples"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "datasets>=3.1.0",
    "matplotlib>=3.7.5",
    "numpy>=1.24.4",
]
