[book]
authors = ["j4orz"]
language = "en"
src = "src"
title = "SITP"

[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = ["theme/css/custom.css"]

[preprocessor.repl]
src = "https://mr-addict.github.io/mdbook-repl/embed/"
python.enable = true
python.loading = "lazy"

[preprocessor.embedify]
giscus.enable = true
giscus.repo = "j4orz/teenygrad"
giscus.repo-id = "R_XXXXXXXXXX"
giscus.category = "General"
giscus.category-id = "DIC_XXXXXXXXXXXXXXXX"
giscus.reactions-enabled = "1"
giscus.theme = "book"
giscus.lang = "en"
giscus.loading = "eager"